// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Photo_Booth_Server_API.Data;

#nullable disable

namespace Photo_Booth_Server_API.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Photo_Booth_Server_API.Models.ImageFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ImageFiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FilePath = "path/to/image1.jpg",
                            Subject = "Sample Image 1"
                        },
                        new
                        {
                            Id = 2,
                            FilePath = "path/to/image2.jpg",
                            Subject = "Sample Image 2"
                        },
                        new
                        {
                            Id = 3,
                            FilePath = "path/to/image3.jpg",
                            Subject = "Sample Image 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
